# Generated by Django 5.2.6 on 2025-09-10 15:11

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('base_sku', models.CharField(help_text='Base Stock Keeping Unit for the product line.', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('unique_sku', models.CharField(help_text='Unique SKU for this specific variant.', max_length=100, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='stock_api.product')),
            ],
            options={
                'unique_together': {('product', 'size', 'color')},
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_change', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, help_text="e.g., 'Venta Tienda Física, boleta #1234' or 'Ajuste de inventario'", max_length=255, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_api.location')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_api.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='StockLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_api.location')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock_api.productvariant')),
            ],
            options={
                'unique_together': {('product_variant', 'location')},
            },
        ),
    ]
